# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Expose the PostgreSQL port (default: 5432)
EXPOSE 5432

# Environment variables for PostgreSQL configuration (optional)
ENV POSTGRES_DB=proxy-golang
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin


