version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proxy-golang
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - app-network

  go-app:
    build:
      context: .
      dockerfile: Dockerfile.go-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
